name: Java CI

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: maven

      - name: Rodar build e testes
        run: mvn clean verify